# Generated by Django 5.2.8 on 2025-11-16 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('avatar', models.FileField(upload_to='avatars/', verbose_name='Аватарка')),
                ('top_photo', models.FileField(upload_to='top_photos/', verbose_name='Фото верхнее')),
                ('friend_link', models.CharField(max_length=500, unique=True, verbose_name='Ссылка на друзей')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Платная/бесплатно')),
                ('is_requested', models.BooleanField(default=False, verbose_name='Просилась или нет')),
                ('categories', models.ManyToManyField(to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Основная модель',
                'verbose_name_plural': 'Основные модели',
            },
        ),
    ]
