# Generated by Django 5.2.8 on 2025-11-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='link_ak',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Ссылка на аккаунт'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='api.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='friend_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на друзей'),
        ),
    ]
