# Generated by Django 5.2.8 on 2025-11-26 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mainmodel_link_ak_alter_mainmodel_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmodel',
            name='friend_link',
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка на друга')),
                ('main_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_links', to='api.mainmodel')),
            ],
            options={
                'verbose_name': 'Ссылка на друга',
                'verbose_name_plural': 'Ссылки на друзей',
                'unique_together': {('main_model', 'url')},
            },
        ),
    ]
