# Generated by Django 5.2.8 on 2025-11-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_mainmodel_friend_link_friendlink'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendlink',
            unique_together={('url',)},
        ),
    ]
