# Generated by Django 5.2.8 on 2026-02-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_friendlink_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alias',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Alias для URL'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('for_home_page', models.BooleanField(default=False, verbose_name='Для главной страницы')),
                ('for_category_pages', models.BooleanField(default=True, verbose_name='Для страниц категорий')),
                ('categories', models.ManyToManyField(blank=True, to='api.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Частый вопрос',
                'verbose_name_plural': 'Частые вопросы',
                'ordering': ['order'],
            },
        ),
    ]
