# Generated by Django 5.2.8 on 2026-02-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_restore_lost_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название (RU)'),
        ),
    ]
