# Generated by Django 5.2.8 on 2026-03-06 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_set_site_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (EN)')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
                ('meta_title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title (RU)')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title (EN)')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='Meta Description (RU)')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta Description (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Категория новостей',
                'verbose_name_plural': 'Категории новостей',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=300, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=300, verbose_name='Title (EN)')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='URL')),
                ('meta_title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title (RU)')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title (EN)')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='Meta Description (RU)')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta Description (EN)')),
                ('meta_keywords_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Keywords (RU)')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Keywords (EN)')),
                ('short_description_ru', models.TextField(verbose_name='Краткое описание (RU)')),
                ('short_description_en', models.TextField(verbose_name='Short Description (EN)')),
                ('content_ru', models.TextField(verbose_name='Содержание (RU)')),
                ('content_en', models.TextField(verbose_name='Content (EN)')),
                ('preview_image', models.ImageField(upload_to='blog/previews/', verbose_name='Превью-изображение')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='blog/main/', verbose_name='Основное изображение')),
                ('author_name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('author_bio_ru', models.TextField(blank=True, null=True, verbose_name='Биография автора (RU)')),
                ('author_bio_en', models.TextField(blank=True, null=True, verbose_name='Author Bio (EN)')),
                ('author_avatar', models.ImageField(blank=True, null=True, upload_to='blog/authors/', verbose_name='Фото автора')),
                ('expert_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя эксперта (проверил)')),
                ('expert_title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность эксперта (RU)')),
                ('expert_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Expert Title (EN)')),
                ('expert_avatar', models.ImageField(blank=True, null=True, upload_to='blog/experts/', verbose_name='Фото эксперта')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('tags', models.CharField(blank=True, max_length=500, null=True, verbose_name='Теги (через запятую)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('reading_time', models.PositiveIntegerField(default=5, verbose_name='Время чтения (минут)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Избранная новость')),
                ('is_breaking', models.BooleanField(default=False, verbose_name='Срочная новость')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Разрешить комментарии')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.newscategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
