# Generated by Django 5.2.8 on 2026-03-12 16:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_newscategory_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author_bio_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Author Bio (EN)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author_bio_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Биография автора (RU)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=ckeditor.fields.RichTextField(verbose_name='Content (EN)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=ckeditor.fields.RichTextField(verbose_name='Содержание (RU)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_en',
            field=ckeditor.fields.RichTextField(verbose_name='Short Description (EN)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_ru',
            field=ckeditor.fields.RichTextField(verbose_name='Краткое описание (RU)'),
        ),
    ]
