# Generated by Django 5.2.8 on 2026-03-12 16:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_news_author_bio_en_alter_news_author_bio_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание (RU)'),
        ),
    ]
